/**
 * Writes `test/fixtures/web_vectors.json` — the envelopes the Flutter test
 * (`test/web_crypto_interop_test.dart`) decrypts to prove Web → Dart interop.
 *
 *   npm run gen:vectors
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { encryptField, encryptBytes } from '../src/crypto/te2';
import { base64Encode, concat, utf8 } from '../src/crypto/bytes';
import { nonceHash, publicKeyFingerprint } from '../src/crypto/pairing';
import { createPairingCode } from '../src/session/pairingCode';
import { encryptPayload } from '../src/trip/sensitivity';
import pairingKeys from '../test/fixtures/pairing_keys.json' with { type: 'json' };

const PRIMARY_KEY = 'dHJpcGVhc2UtdGVzdC10cmlwLWtleS0wMDAxLWFhYWE=';

const PLAINTEXTS: Record<string, string> = {
  empty: '',
  ascii: 'hello world',
  hebrew: 'טיול לרומא — מלון ליד הקולוסאום',
  emoji: 'Flight AZ123 ✈️ seat 14A',
  blockAligned: '0123456789abcdef',
  blockAlignedPlusOne: '0123456789abcdef0',
  long:
    'A long free-form note that spans several AES blocks so the CTR counter ' +
    'has to increment more than once. 0123456789 0123456789 0123456789 ' +
    '0123456789 0123456789 0123456789 0123456789 0123456789.',
};

/**
 * A legacy (pre-v2) envelope: `iv | AES-CTR(PKCS7(plaintext))` keyed directly
 * with the master key, no magic and no tag. Built here by hand because the
 * production code only ever writes v2.
 */
async function legacyEnvelope(plaintext: string, base64Key: string): Promise<string> {
  const iv = new Uint8Array(16);
  crypto.getRandomValues(iv);
  const masterKey = Uint8Array.from(Buffer.from(base64Key, 'base64'));
  const cryptoKey = await crypto.subtle.importKey('raw', masterKey, { name: 'AES-CTR' }, false, [
    'encrypt',
  ]);
  const input = utf8(plaintext);
  const padLength = 16 - (input.length % 16);
  const padded = new Uint8Array(input.length + padLength);
  padded.set(input, 0);
  padded.fill(padLength, input.length);
  const ciphertext = new Uint8Array(
    await crypto.subtle.encrypt({ name: 'AES-CTR', counter: iv, length: 128 }, cryptoKey, padded),
  );
  return base64Encode(concat(iv, ciphertext));
}

async function main() {
  const te2 = await Promise.all(
    Object.entries(PLAINTEXTS).map(async ([name, plaintext]) => ({
      name,
      key: PRIMARY_KEY,
      plaintext,
      ciphertext: await encryptField(plaintext, PRIMARY_KEY),
    })),
  );

  // A binary payload too — attachments go through the same envelope.
  const binary = new Uint8Array(300);
  for (let i = 0; i < binary.length; i += 1) binary[i] = (i * 7) % 256;

  const sensitive = await encryptPayload(
    {
      notesData: [{ id: 'n1', title: 'כרטיסים', content: 'קוד הזמנה ABC-123' }],
      logisticsData: [
        {
          id: 'l1',
          mainType: 'hotel',
          name: 'Hotel Roma',
          notes: 'צ׳ק־אין מאוחר',
          address: 'Via Cavour 1',
          totalPrice: 420.5,
        },
      ],
      bookingConfirmationsData: [{ id: 'b1', orderNumber: 'XY-99', price: 120 }],
      documentsData: [{ id: 'd1', name: 'דרכון', description: 'סרוק' }],
    },
    PRIMARY_KEY,
  );

  // The pairing nonce *is* the 8-character code shown next to the QR.
  const nonce = createPairingCode();

  const vectors = {
    _note:
      'Generated by apps/web/scripts/generate-web-vectors.ts. Consumed by the ' +
      "Flutter test test/web_crypto_interop_test.dart. Test-only keys — they open nothing real.",
    generator: 'web',
    keys: { primary: PRIMARY_KEY },
    te2,
    binary: {
      key: PRIMARY_KEY,
      plaintextBase64: base64Encode(binary),
      ciphertext: base64Encode(await encryptBytes(binary, PRIMARY_KEY)),
    },
    legacy: {
      key: PRIMARY_KEY,
      plaintext: 'a legacy envelope with no magic and no tag',
      ciphertext: await legacyEnvelope('a legacy envelope with no magic and no tag', PRIMARY_KEY),
    },
    sensitivePayload: {
      key: PRIMARY_KEY,
      encrypted: JSON.stringify(sensitive),
      expectedNote: 'קוד הזמנה ABC-123',
      expectedLogisticsNote: 'צ׳ק־אין מאוחר',
    },
    pairing: {
      nonce,
      // The app normalises before hashing, so a typed `abcd-2345` and a
      // scanned `ABCD2345` land on the same digest.
      nonceHashFromTypedForm: await nonceHash(
        `${nonce.slice(0, 4).toLowerCase()}-${nonce.slice(4).toLowerCase()}`,
      ),
      nonceHash: await nonceHash(nonce),
      browserFingerprint: await publicKeyFingerprint(pairingKeys.browser.publicKeyRaw),
    },
  };

  const target = join(dirname(fileURLToPath(import.meta.url)), '../test/fixtures/web_vectors.json');
  writeFileSync(target, `${JSON.stringify(vectors, null, 2)}\n`);
  console.log(`wrote ${target}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
